FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Goodman Set-Cookie Testing

Testing an error that happens when an API gives Goodman a Set-Cookie header

# Group Testing

## Cookie Collection [/]

## Cookie-Cookie [POST /cookie-cookie]

+ Response 200

## Set-Cookie [POST /set-cookie]

+ Response 200
